### ISSUE TITLE
Just a hint.

### ISSUE THREAD

**Issue by p410n3** [kunkliricsi/CATSBot2#1]
You can make a ne branch on the Catsbot repository instead of mnaking a whole new repository. Nice addition tho

**Comment by kunklir** [comment]
I thought I'm gonna test stuff on my repo, so i won't screw up anything on yours. Once everything is set we can upload the code to yours aswell. Btw I'm done with a new update and I'm going to publish it here first, then if everything checks out, we may move it there.

**Comment by kunklir** [comment]
To be honest, I'm a noob with github... Sorry to cause any trouble.

**Comment by p410n3** [comment]
Haha no problem at all. Just looked at the Big Update. Holy Shit! Awesome stuff. (I think... its way too much for me to read.) If you think the versionis fine feel free to release it on our website. Maybe make a lil video I dont know. I will add you to the team then.
