### ISSUE TITLE
Did You Bail

### ISSUE THREAD

**Issue by BWG7** [kunkliricsi/CATSBot2#6]
Hey, I still use it to quick fight. Did you abandon this project/game?

**Comment by kunklir** [comment]
Yea sorry, I don't have much time to work on this.

**Comment by p410n3** [comment]
> Hey, I still use it to quick fight. Did you abandon this project/game?

The original bot was from @1n9i9c7om with some little help from me and we both have no time either. Just so you know.

**Comment by BWG7** [comment]
It still semi-works, which is funny. Thanks for doing it!

Hope all is well. Take care.
